export const CHANGE_HOME_DATA = 'home/CHANGE_HOME_DATA'
export const CHANGE_AUTHORLIST_PAGE = 'home/CHANGE_AUTHORLIST_PAGE'
export const ADD_ARTICLE_LIST = 'home/ADD_ARTICLE_LIST'
export const TOGGLE_BACKTOP_SHOW = 'home/TOGGLE_BACKTOP_SHOW'